### PR TITLE
Ammo performance improvements

### PR DESCRIPTION
**Pull request by diarmidmackenzie**
Basic set of Ammo perf improvements, as per #15.

One slight hesitation about this is that people who have used previous versions of aframe-physics-system, and disregarded the rules about not moving static entities could have bugs exposed by moving to this version.

When we publish the version containing tis fix, we should add a note to the release note about that.

I *don't* think it's worth preserving the old behaviour with a flag, because the old behaviour is bugged, and I don't want to have to preserve bugged behaviour forever.

### CODE REVIEW

**Comment by diarmidmackenzie** [comment]
On my PC, I'm seeing median tick "before" perf reduce from ~1.5msecs to ~0.5msecs with these fixes.

Overall median tick reduces from ~3.5msecs to ~2.5 msecs.

**Comment by kylebakerio** [comment]
nice!

we could leave in some kind of `.error()` check for an attempt to move a static body being caught, with an explanation that they should change it to a kinematic body?

**Comment by kylebakerio** [comment]
Weird, why don't I see the `syncToPhysics()` function body here? Was it added previously?

**Comment by diarmidmackenzie** [comment]
> Weird, why don't I see the `syncToPhysics()` function body here? Was it added previously?

Not sure where you are looking... 

It's here:
https://github.com/c-frame/aframe-physics-system/blob/78290ee312bf0b7616942ec966203e3b42670c18/src/components/body/ammo-body.js#L373

**Comment by diarmidmackenzie** [comment]
> we could leave in some kind of `.error()` check for an attempt to move a static body being caught, with an explanation that they should change it to a kinematic body?

I don't see how to do this efficiently.

Inefficient options I can see are:
- check latest position vs. previous position every tick.  But that means checking every static object every tick.
- listen for the componentchanged event on a static object, in case the position component is updated.  But (a) that won't detect position changes made direct to the Object3D (which is the recommended way to update position) and (b) it requires code that executes every time any component on any static object changes.

**Pull request merged**
