### PR TITLE
Clean up logic around body removal

### PR DESCRIPTION
**Pull request by diarmidmackenzie**
As per #47, there are some issues with ammo body removal.

This is an attempt to clean up the logic and make it more closely mirror what happens when an ammo body is added.

I think the simple fix suggested in #47 likely leaves fails to address some more subtle issues, by not doing a full clean-up.

I don't have a great way of testing this yet - the existng examples all recycle entities rather than destroying and respawning them.  Maybe I should update one of those examples...

### CODE REVIEW

**Comment by diarmidmackenzie** [comment]
OK - the pinboard (perf) example does destory and recreate the objects, and is executing the new code, without issues.

A-Frame inspector pause/play on the scene is also still working OK.

So looks like there's no obvious major regressions.

But neither of those tests exhibited problems before, so no evidence yet that we have fixed the problem.

From #47, and the previous issue raised on the old version of this repo, I found this glitch.
https://aframe-physics-ammo2.glitch.me/

Updated to latest code.  Still seeing problems - after deleting an object (by pressing a key), the next object doesn't reliably switch to blue on collision.
https://aframe-physics-system-issue-47.glitch.me/

That suggests that #47 is still not fixed by these changes.

**Comment by diarmidmackenzie** [comment]
Have done a bunch of testing with the example here https://aframe-physics-system-issue-47.glitch.me/.

Removing the line
```
//Ammo.destroy(this.body);
```
seems to solve the issue.  I don't understand why that would be, though - and I would be worried about memory leaks.

**Comment by diarmidmackenzie** [comment]
Thanks.  However at this point I don't understand the fix.  The key thing that makes the fix work appears to be removing the call to `Ammo.destroy(this.body)`.

I don't understand why that would make any difference, and it seems problematic in that it leaks memory.

**Comment by diarmidmackenzie** [comment]
Replacing

```
Ammo.destroy(this.body)
```

with

```
setTimeout(() => Ammo.destroy(this.body))
```

seems to fix the issue & should prevent a memory leak.

So I guess there is some further reference to the body that is being invoked after `remove()` is called on `ammo-body`, and that leads to probems if the Ammo body has been destoryed.

I wonder whether `ammo-shape` `remove()` gets called ater `ammo-body`.  `ammo-shape` has a reference to the body and tries to do things with it in its `remove()` processing.

**Comment by diarmidmackenzie** [comment]
OK - so there is a definite potential issue here that `ammo-body` gets removed before `ammo-shape`, but `ammo-shape` removal seems to assume that `ammo-body` state is still usable.

Digging into this further...

**Comment by Elettrotecnica** [comment]
Not sure how helpful this is, but in my use case I need to switch the body type of entities dynamically when their ownership changes (it is a networked experience). 

I have also encountered some problems when removing the ammo components and this is the piece of code that I found to be working reliably. Maybe will give some hint on the add/remove lifecycle.

`
        //
        // Switch entities physics when they are grabbed/released from
        // dynamic (local) to kinematic (remote).
        //
        function switchBodyType(e, type) {
            const shape = e.getAttribute('ammo-shape');
            if (e.components['ammo-body'].addedToSystem) {
                e.removeAttribute('ammo-shape');
                e.removeAttribute('ammo-body');
            }
            e.setAttribute('ammo-body', type);
            e.setAttribute('ammo-shape', shape);
        }
`

**Comment by diarmidmackenzie** [comment]
Among other changes, the fix I proposed automaticaly deletes the `ammo-shape` attribute on removal of the `ammo-body` attribute.

That makes sense when the whole element is being removed, but it doesn't make sense in the case where `ammo-body` is removed via a call to `removeAttribute()`.  That could cause a lot of confusion.

It might be better to fix `ammo-shape` `remove()` code to better handle the case where `ammo-body` has already been removed...

**Comment by diarmidmackenzie** [comment]
This code is complicated, with very little symmetry between creation & deletion which makes it hard to reason about.  We really need some unit tests to cover all the scenarios...

How does it all work?
- `ammo-shape` component calls `addShapeComponent()` on the `ammo-body`
- `ammo-body` maintains a list of shape components, then every physics tick, in `_updateShapes` it checks for changes, works through that list and cals into three-to-ammo to create a new `collisionShape` for each shape that doesn't already have one.
- it also stores a reference to the `collisionShape` back inside the shape component (via `.addShapes()`)

When a shape component gets removed, the shape component removes the shape component from `ammo-body`'s list (so it won't get created on the next tick, and calls the `destroy()` function on that stored `collisionShape`, which is how the actual Ammo shape gets destroyed (this is how the three-to-ammo API exposes `Ammo.destroy()` for these shapes).  Not clear to me whether or not this will work if the `ammo-body` component has already been removed.  (I think the fact that the fact that `ammo-shape` still has a reference to the component at `this.body` means things should still work.

The shape component is also responsible for calling `Ammo.destroy(collisionShape.localTransform)`, which was created by three.to-ammo (but which three-to-ammo for some reason doesn't take responsibility for destroying when `collisionShape.destroy()` is called...)

I can't see any actual gaps in the above, but it's hard to reason about, and hard to be confident without Unit Tests.

Not sure where to go with this.  I don't like the PR as it stands.  Probably next step is some Unit Tests, and maybe some refactoring to simplify the above.

But inthe short term, maybe we should go with the simplest fix possible and which would be just this...

```
      if (!this.data.emitCollisionEvents) {
        // As per issue 47 / PR 48 there is a strange bug
        // not yet understood, where destroying an Ammo body 
        // leads to subsequent issues reporting collision events.
        // 
        // So if we are reporting collision events, preferable to
        // tolerate a small memory leak, by not destroying the 
        // Ammo body, rather than missing collision events.
        Ammo.destroy(body);
      }
```

**Pull request closed without merging**
