### PR TITLE
Fix various bugs

### PR DESCRIPTION
**Pull request by diarmidmackenzie**
- allow for the fact that ancestors may be scaled when computing scale
- allow for THREE.js scene graph to vary from the HTML scene graph
- defensive code for race conditions where collisionShape is undefined.

All these fixes have been live-tested fairly extensively in the context of my [Christmas scene](https://github.com/diarmidmackenzie/christmas-scene/) experience.

No unit tests or examples yet for this repo.
- Unit Tests would be nice, but there's a big job to extend the UTs from the current minimal set.
- I can pull together a set of examples fairly easily, but propose doing that as a separate PR.

### CODE REVIEW

**Comment by kylebakerio** [comment]
Nice, thanks for this! These make sense to me overall, but to play devil's advocate for due dillegence:

> allow for THREE.js scene graph to vary from the HTML scene graph

Any thoughts on this causing confusion or issues? Any reason we should hesitate here or alternate approaches that would be worth considering.

A reparenting example and an explanation of your intentions & use case there would also be helpful. How did you use this feature in your christmas scene?

**Review by vincentfretin — COMMENTED** [review]
This is good overall.
There is only the parentEl change that I don't understand.
In which case `el.parentEl` is something different than `el.object3D.parent.el`? Those two should be the same generally no?

**Comment by vincentfretin** [comment]
I read again your PR description and @kylebakerio comment for the reparenting feature, so you mean you're resetting object3D.parent in some other code, probably here https://github.com/diarmidmackenzie/christmas-scene/blob/9853ed99311aea9d66c6bd261ff1d86e2aa91dec/src/move-objects.js#L12
You should include a comment in the code, because it doesn't make sense to me just reading the changed line because `el.parentEl` is the same as `el.object3D.parent.el` in a normal case.

**Comment by diarmidmackenzie** [comment]
Thanks for the comments.  I find myself having to modify the THREEjs scene graph so it doesn't match the HTML scene graph pretty regularly.

Useful for e.g.
- grabbing entities with a controller or the mouse 
https://diarmidmackenzie.github.io/aframe-examples/component-usage/mouse-manipulation.html

- blended transforms 
https://diarmidmackenzie.github.io/screen-display/examples/example-transform-reverse.html

- sticking objects together that aren't spawned as HTML parent-child
https://twitter.com/dhmackenzie/status/1472711776865337344?s=20&t=J9ckp83r0b6idmcyBFxKvw

> Any thoughts on this causing confusion or issues? Any reason we should hesitate here or alternate approaches that would be worth considering.

I don't think so.  I use it a lot, never have any issues, it's an approach recommended by  A-Frame maintainers.
Here:
https://stackoverflow.com/questions/52318200/change-parent-of-component-and-keep-position
and here:
https://github.com/aframevr/aframe/issues/2425#issuecomment-292643948

I also have implemented a dedicated component that simplifies the implementation (though I ought to fix this up to use `object3D.attach` instead of `.add`, which I've recently discovered is a much cleaner way to implement this).
https://diarmidmackenzie.github.io/aframe-examples/docs/object-parent.html

Didn't realize this technique was no widely known.  I will add a comment to the code here as per your suggestions, and try to write a wiki article about it at some point...

**Comment by kylebakerio** [comment]
Yeah, a general glitch showing reparenting for the e.g. elevator example would be cool. In theory it makes perfect sense to me, I've just never needed that feature yet.

**Comment by vincentfretin** [comment]
Same here, I never needed such feature so I wasn't aware of it all. I don't do much VR stuff so I never had the need to grab things and do reparenting.
It's the first time I see your [aframe-examples](https://github.com/diarmidmackenzie/aframe-examples) repo, nice things there.

**Pull request merged**
